apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 92.1.1
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/infrastructure/observability/kube-prometheus-stack/values.yaml
    - repoURL: https://github.com/gka038/next-gen-cicd
      targetRevision: fm/ngc-1
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
