{{- if .Values.components.workflows }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repo.url }}
    targetRevision: {{ .Values.repo.targetRevision }}
    path: infrastructure/workflows
    directory:
      recurse: true
      include: "**/application.yaml"
  destination:
    server: {{ .Values.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
