apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.19.2
      helm:
        releaseName: harbor
        valueFiles:
          - $values/infrastructure/registry/harbor/values.yaml
    - repoURL: https://github.com/gka038/next-gen-cicd
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
